README.md
app/.graphqlconfig
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Kafka.kt
http/dev-graphql-query.http

vi kan ikke gjøre en ny poll dersom vi har en pågående feil. Det vil forårsake at vi går videre og hopper over feilende records.

simple retry med multiplying backoff.

---

app/Dockerfile
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Database.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Main.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/QueryModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/graphql/BrukerAPI.kt
app/src/main/resources/db/migration/V2__opprett_notifikasjon.sql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/GraphQLTests.kt

notifikasjoner med db.
lagt inn scuttle og dumb init for å vente ti listio er klar.
poller også til db er klar før migrering kjører. Tar litt tid før riktig secrets er på plass på gcp.

Notifikasjoner db

---

app/pom.xml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Kafka.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/EmbeddedKafkaTestListener.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/GraphQLTests.kt

test og verifiser mot embedded kafka i stedet for mockk

Embedded kafka

---

.github/workflows/build.yaml
.gitignore
app/src/main/kotlin/db/migration/MigrationOps.kt
app/src/main/kotlin/db/migration/V1__RebuildQueryModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Main.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Kafka.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/LocalMain.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/QueryModelTests.kt
config/nais-kafka-topic.yaml
download_kafka_cli.sh

Er litt mismatch mellom oppsett lokalt og i docker/k8s. Derfor litt lim i `MigrationOps`

Rebuild projections vha flyway migration

---

app/pom.xml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/BrukerAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Main.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Brreg.kt
app/src/main/resources/bruker.graphqls
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/BrregTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/BrukerApiTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/BrukerKlikkGraphQL_QueryModell_Integrasjon.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/KlikkPåNotifikasjonGraphQLTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ProdusentApiTests.kt

med enkel lrucache som refreshes etter 12h.
virksomhet berikes med navn fra brreg dersom graphql query har bedt om navn på virksomhet.

slå opp virksomhetsnavn i brreg

---

README.md
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Hendelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Kafka.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/SlettHendelseTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/SlettNotifikasjonTests.kt
config/nais-kafka-topic.yaml

lagt til slett hendelse inklusiv test med kafka listener

Poc delete

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Hendelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ProdusentAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/QueryModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/GraphQL.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Kafka.kt
app/src/main/resources/produsent.graphqls
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/BrukerApiTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/QueryModelTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/InputValideringTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/NyBeskjedTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/NyOppgaveTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/TilgangsstyringTests.kt

Legger til endepunkt i produsent-api, og oppretter notifikasjoner (dog som beskjed). Mangler med andre ord et felt i databasen for å skille beskjed og oppgave fra hverandre.

Graphql oppgaver

---

config/nais-application.yaml
config/nais-kafka-topic.yaml

Må legge til inbound i altinn-rettigheter-proxy.

Bytt namespace til fager

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/BrukerAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/QueryModel.kt
app/src/main/resources/db/migration/V1__start_oppsett.sql

Her lagres det i databasen hvorvidt det er en beskjed eller oppgave. Mangler å oppdatere bruker-api.

Oppdater query model: skill mellom beskjed/oppgave

---

.graphqlconfig
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/BrukerAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/GraphQL.kt
app/src/main/resources/bruker.graphqls
app/src/main/resources/produsent.graphqls
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker_api/BrukerApiTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/executable/LocalMain.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/AltinnStub.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/BrregStub.kt

propagerer tilstanden fra query-model til bruker-api.

Legger på tilstand til frontend

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentModel.kt
app/src/main/resources/produsent.graphqls
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/MineNotifikasjonerTests.kt

legger til hentNotifikasjoner for merkelapp med paginering basert på relay connection https://relay.dev/graphql/connections.htm

Mine notifikasjoner produsent

---

app/Dockerfile
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/NærmesteLederService.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/NærmesteLederServiceTests.kt
download_kafka_cli.sh

Dette skjer i prod ganske ofte:
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
at [Source: (String)""; line: 1, column: 0]
at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4344)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4189)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
at io.ktor.client.features.json.JacksonSerializer.read(JacksonSerializer.kt:24)
at io.ktor.client.features.json.JsonSerializer$DefaultImpls.read(JsonSerializer.kt:31)
at io.ktor.client.features.json.JacksonSerializer.read(JacksonSerializer.kt:14)
at …
```

håndter at syfo returnerer 200 ok med tom body

---

.github/workflows/cicd.yaml
app/pom.xml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/wsclient/AltinnVarselKlient.kt

for å teste dette trenger vi brukernavn og passord i tt02.
Vi kan gå rett på tt02 fra gcp uten sertfikat så vidt jeg skjønte, men det er mulig noe med må gjøres i kulissene.
undersøker dette med team altinn.
ref:
https://nav-it.slack.com/archives/C8QHLER2Q/p1609944607177300?thread_ts=1608564408.135300&cid=C8QHLER2Q
https://nav-it.slack.com/archives/CDTFB525A/p1632736177005600?thread_ts=1632475797.002800&cid=CDTFB525A

la til AltinnVarselKlient som benytter soap til å sende varsel til virksomhet

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Health.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/ProcessingLoop.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/kafka/CoroutineKafkaConsumer.kt

Ser ut til å fungere fint i dev hvis man sletter pod-en.
De trådene som sover veldig lenge (10 minutter) merker ikke at man har fått avslutte-signal. Men det burde vel ikke være et problem.

Handle sigterm

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkService.kt

1) Legg til antall notifikasjoner som er klikket på.
Vi har allerede antall klikk. Den teller 15 klikk på samme notifikasjon som 15 klikk.
Denne nye teller ikke flere klikk på samme notifikasjon. Kun hvor mange notifikasjoner
som er klikket på≥
2) Juster utført-historgramet.
infinity-bucketen inneholdte også de som ikke er utført.
Presiserer at det er 4W-infinity, og teller kun utførte.

Oppdater metrics om klikk/utført

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Database.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Util.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyBeskjed.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyOppgave.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/QueryMineNotifikasjoner.kt
app/src/main/resources/produsent.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/EksternVarselApiTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/HardDeleteNotifikasjonTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/MineNotifikasjonerTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/NyBeskjedTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/NyOppgaveTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/SoftDeleteNotifikasjonTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/PostgresTestListener.kt

fikk en ide for hvordan håndtere joins

---

app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/EnsureTestFileNameListener.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/IdempotensOppførselForProdusentApiTests.kt

finner feil ved lokal kjøring i idea

sjekk filnavn til alle tester

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
config/dev-gcp-produsent-api.yaml

oppdater accesspolicy til å reflektere appen som kaller oss

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/AltinnVarselKlient.kt

Testet i dev:
```
Headers: {Authorization=XXX, SOAPAction="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAgencyExternalBasic/SendStandaloneNotificationBasicV3", Accept=*/*}
```

mask authorization header

---

app/src/main/resources/db/migration/bruker_model/V7__mottaker_nullable.sql
app/src/main/resources/db/migration/bruker_model/V8__drop_cruft.sql

vent til nyeste versjon er deployet, siden den ikke leser disse.

mottaker er nullable nå

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt

vil komme en PR etter dette, som sletter kolonnen og innfører "not null" på virksomhetsnummer

stopp med a skrive mottaker i produsent-model

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Hendelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkModel.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/HendelseDeserializationTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/NyBeskjedTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/NyOppgaveTests.kt

Statistikk støtter nå flere mottakere. Alle tjenestene støtter dermed flere mottakere. Siste steg er å legge til støtte i graphql for dette.

Statistikk flere mottakere

---

app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/LokalOsloTidTests.kt

fiks LokalOsloTidTests

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Hendelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegister.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyNotifikasjonFelles.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/QueryMineNotifikasjoner.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkModel.kt
app/src/main/resources/db/migration/produsent_model/V9__altinn_reportee_mottaker.sql
app/src/main/resources/produsent.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/Common.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/NyBeskjedFlereMottakereTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/EksempelHendelser.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/PostgresTestListener.kt

Denne PR legger altinn reportee til i produsent api både i graphql domene og database modell
Neste steg blir å implementere tilgangsstyring i bruker api for denne mottakertypen

legg til mottaker for altinn reportee i produsent api

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNySak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationOppdaterSak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/ProdusentAPI.kt
app/src/main/resources/produsent.graphql

Jeg begynte å implementere modeller og sånt, men vi burde kanskje se på graphql-skjemaet for seg selv først.

produsent-api-graphql-skjema for innsyn i sak

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Altinn.kt
app/src/main/resources/db/migration/bruker_model/V10__altinn_rolle_mottaker.sql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker_api/AltinnRolleTilgangsstyringTests.kt

Selve kallet ti l altinn for oppslag basert på mottakerregister kommer i neste PR

legg til støtte for altinn rolle i bruker api

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Enhetsregisteret.kt

https://jira.adeo.no/browse/TAG-1849

Robust kall mot ereg

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt

fikser også accessPolicy som ser ut til å ha blitt feil

fiks id til å matche endring i yaml

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
config/dev-gcp-produsent-api.yaml
config/prod-gcp-produsent-api.yaml

som definert i 
* https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/8

oppdaterer produsentregister med endringer for permittering

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkService.kt
app/src/main/resources/db/migration/statistikk_model/V8__legg_til_saksstatistikk.sql

legg til saksstatistikk

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkModel.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkModelTests.kt

testen er litt teit, men er bare for å verifisere at ingenting stopper opp når vi får en hendelse som er for en av aggregattypene

legger til oppdatering av soft_deleted_tidspunkt for sak

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/Error.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/HendelseDispatcher.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationHardDeleteNotifikasjon.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationHardDeleteSak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyBeskjed.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyOppgave.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNySak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyStatusSak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationOppgaveUtfoert.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationSoftDeleteNotifikasjon.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationSoftDeleteSak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/ProdusentAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/Util.kt
app/src/main/resources/produsent.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/HardDeleteNotifikasjonTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/HardDeleteSakTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/SoftDeleteNotifikasjonTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/SoftDeleteSakTests.kt

API og generering av hendelse for manuell sletting av sak.
Ikke implementert:
- Ingen av konsumenterene håndterer den. De vil vel ignorere den.

sletting av sak

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Hendelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/ISO8601Period.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/Scalars.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/FellesGraphQLTypes.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/autoslett/ScheduledTimeTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/ISO8601PeriodTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NySakTests.kt

Java-klassene Duration og Period fanger ikke inn hele ISO8601-duration.
Lager en egen klasse som gjør det.

Egen ISO8601-Duration-klasse

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/EksternVarsling.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingService.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/Åpningstider.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/logging/LogConfig.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingServiceTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/ÅpningstiderTests.kt

åpningstider.nå gir ikke mening, så denne flyttes til LokalOsloTid.

forenkling av åpningstider

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
config/dev-gcp-produsent-api.yaml

ref:
- https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/11

oppdater prosdusent definisjon for esyfovarsel

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt

- https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/12

endre tilgangsstyring for team permittering

---

app/pom.xml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/altinn_roller/AltinnRolleClient.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Enhetsregisteret.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/HttpClientMetricsFeature.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/SuspendingAltinnClient.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/GraphQL.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/http/HttpAuthProviders.kt

Moarmetrics

---

app/src/main/resources/db/migration/produsent_model/V12__indekser_mottakere.sql

I Query Inspector i google cloud console, så kan vi se at
kjøretiden for spørring i produsent-api vokser. Det er grunnet
flere sekvensielle scans.
Dette er en sammenligning av av `explain ProdusentRepositoryImpl.hentNotifikasjon(?id?: UUID)`
før migrering og etter migering. Legg merke til "Seq Scan".
Før migering:
Hash Left Join  (cost=20.94..113.06 rows=432 width=352)
Hash Cond: (notifikasjon.id = ev.notifikasjon_id)
->  Nested Loop Left Join  (cost=0.14..78.90 rows=108 width=416)
->  Hash  (cost=20.75..20.75 rows=4 width=48)
Join Filter: (mar.notifikasjon_id = notifikasjon.id)
->  Subquery Scan on ev  (cost=0.00..20.75 rows=4 width=48)
->  Nested Loop Left Join  (cost=0.14..59.37 rows=27 width=384)
->  Materialize  (cost=0.00..18.89 rows=4 width=48)
Join Filter: (maro.notifikasjon_id = …

Indekser for oppslag i produsent-api.

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
config/prod-gcp-produsent-api.yaml

- https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/13

enable esyfo produsent i prod

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/logging/MaskingAppender.kt

mangler testdekning på log oppsettet, men fant ikke en god nok måte å teste dette på.
testet det manuelt og det fungerer som det skal.

legg til maskering av throwableproxy.message også

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/Bruker.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Altinn.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/AltinnCachedImplTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/AltinnImplTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/EmbeddedKafkaTestListener.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/KtorTestServer.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/PostgresTestListener.kt

legg til caching av tilganger kall mot altinn og ta dette i bruk i bruker api
litt usikker på hva som er fornuftig max og expiry. Vi har sagt max 30 min, så starter med 10 min og 10_000 entries ¯\_(ツ)_/¯

Tag 1797 cache altinn

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt

https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/commit/cb5982905747b5b3e84b520fe088ca73bf489212

oppdater tjenestekoder for tiltak

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt

se: 
- https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/16

oppdater definisjon av esyfo produsent

---

app/pom.xml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/hendelse/Hendelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Database.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/Scalars.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyOppgave.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/ProdusentAPI.kt
app/src/main/resources/db/migration/bruker_model/V16__notifikasjon_add_column_frist.sql
app/src/main/resources/produsent.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/HendelseSerializationTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/autoslett/AutoSlettRepositoryEventIntakeTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/OppgaveUtgåttTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepositoryTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingServiceTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EmergencyBreakTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/IdempotentOppgaveOpprettetTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/HardDeleteNotifikasjonTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MineNotifikasjonerTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyOppgaveTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/OppgaveUtførtTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/OppgaveUtgåttTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/SoftDeleteNotifikasjonTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkModelTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/EksempelHendelser.kt
docker-compose.yml

Legg på frist i produsent-api og ut i eventer på Kafka. 
Ikke testet ferdig.

Legg på oppgave-frist i eventer

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/autoslett/AutoSlettService.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/GraphQL.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/main/resources/db/migration/produsent_model/V13__add_frist.sql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyOppgaveTests.kt

Legg til frist i modellen til produsent-api. Dette fører til at produsent-api gjør duplikatsjekk riktig.

Lagr frist i produsent-api

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ReplayValidator.kt

ser ut som denne ble disablet i en refactor.
Skrur den på igjen

re enable replay validator

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/resources/bruker.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepositorySearchTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/HardDeleteTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/QuerySakerFristTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/QuerySakerTests.kt

skrev om SQL og fikset paginering.
Fant fort ut at forrige approach ikke lot seg paginere. Gikk derfor for noe nytt og spennende 🤠

sortering av saker

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/AltinnVarselKlient.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarselTilstand.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarsling.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingService.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepositoryTests.kt

plus litt refactoring og tester

legg til manglende implisitt sende_status

---

.github/workflows/cicd.yaml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Database.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/PostgresTestListener.kt
docker-compose.yml

NB: krever at man kjører docker-compose up på nytt

endre postgres port lokalt og i test

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/hendelse/Hendelse.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/HendelseSerializationTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepositoryTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingServiceTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EmergencyBreakTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/IdempotentOppgaveOpprettetTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/InputValideringTests.kt

ref: https://nav-it.slack.com/archives/C02F7211DQ8/p1670412189949659

påkrevd virksomhetsnummer ved opprettelse av notifikasjon og sak

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/hendelse/Hendelse.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/HendelseSerializationTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepositoryTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingServiceTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EmergencyBreakTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/IdempotentOppgaveOpprettetTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/InputValideringTests.kt

Reverts navikt/arbeidsgiver-notifikasjon-produsent-api#369

Revert "påkrevd virksomhetsnummer ved opprettelse av notifikasjon og sak"

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/AltinnVarselKlient.kt

Reverts navikt/arbeidsgiver-notifikasjon-produsent-api#376

Revert "unngå repeated send ved exception i serialisering av respons"

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
config/dev-gcp-produsent-api.yaml

ref:
- https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/18
- https://nav-it.slack.com/archives/C01V9FFEHEK/p1674474958767659

legg til ny produsent toi-arbeidsgiver-notifikasjon

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
config/prod-gcp-produsent-api.yaml

- https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/19

team-toi tilgang i prod-gcp

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/main/resources/db/migration/produsent_model/V15__unique_mottaker.sql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/ProdusentModelIdempotensTests.kt

uniqueness constraint on produsent mottaker-tables

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/Bruker.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/resources/db/migration/bruker_model/V22__unique_mottaker.sql
app/src/main/resources/db/migration/bruker_model/V23__actually_unique_mottaker.sql

Unique mottaker bruker model

---

app/pom.xml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/Bruker.kt
config/dev-gcp-bruker-api.yaml
config/prod-gcp-bruker-api.yaml

Information about blocking in coroutines

Blockhound

---

app/pom.xml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/http/HttpServer.kt

try cio http server engine

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt

se:
- https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/20

ny produsent arbeidsgiver-dialog

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/hendelse/Hendelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationOppgaveUtfoert.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationOppgaveUtgaatt.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_utgått/SkedulertUtgåttService.kt
app/src/main/resources/produsent.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/NyLenkeOppgaveTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/OppgaveUtgåttTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/QuerySakerFristTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/OppgaveUtgåttTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDeleteRepositoryEventIntakeTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseServiceTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_utgått/SkedulertUtgåttServiceTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkModelTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/EksempelHendelser.kt

- https://github.com/navikt/arbeidsgiver-notifikasjon-fake-produsent-api/pull/20

TAG-2044: Legg til støtte for nyLenke i oppgave utført/utgått

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/DataproduktModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/hendelse/Hendelse.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/DataproduktIdempotensTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/EksempelHendelser.kt

som følge av prodfeil 7 Sep. 2022

håndter NyStatusSak på sak som ikke finnes.

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/DataproduktModel.kt
app/src/main/resources/db/migration/dataprodukt_model/V3__grant_access_dataprodukt_service_user.sql

This reverts commit 00d9e25aab9a807d1d23638731153b2bad0a3712.
Now terraform has created the sql user.

Revert "slett db migration in order to run terraform first"

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/Dataprodukt.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/DataproduktModel.kt
app/src/main/resources/db/migration/dataprodukt_model/V5__pseudonymize_contact_info.sql
terraform/bigquery.tf

krever replay av topic fra start for denne comsumer gruppen

legg til manglende data for svar tidspunkt

---

app/src/main/resources/db/migration/dataprodukt_model/V7__new_pseudonymize_function.sql

Gjør kun endring i funksjonen her. Tar ikke og roterer secret eller replayer her, for da er det issues med at vi har flere pods kjørende med gammel og ny kode Så får alle pods over til å bruke den riktige funksjonen først.

Use sha256. crypt includes salt in return value

---

.github/workflows/build-manual.yaml
.github/workflows/cicd.yaml
.github/workflows/deploy-dev-manual.yaml
app/pom.xml

* https://github.com/nais/docker-build-push
* https://github.com/navikt/gar_push_test/blob/main/.github/workflows/push_and_deploy.yaml
* https://nav-it.slack.com/archives/C01DE3M9YBV/p1678459519383899

bytt til ny GAR deployment oppsett i nais

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/AltinnVarselKlient.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/AltinnVarselKlientImplTest.kt

Retry altinn feil med feilkode 44

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/Dataprodukt.kt
app/src/main/resources/db/migration/dataprodukt_model/V10__pseudonymize_lenke_eksternid.sql
terraform/bigquery.tf

burde kanskje merge [denne](https://github.com/navikt/arbeidsgiver-notifikasjon-produsent-api/pull/453) først:
* https://github.com/navikt/arbeidsgiver-notifikasjon-produsent-api/pull/453
TODO:

legg til varsel resultat i dataprodukt og rebuild query model

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/AltinnVarselKlient.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/AltinnVarselKlientImplTest.kt

fikk noen feilkode = 0 når det var problemer med altinn. Disse varslene burde vært forsøkt på nytt

retry feilkode=0

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkModel.kt

statistikk er nå stuck i prod pga helsearbeidsgiver sender varsler til altinn tjeneste

legg til manglende case for altinntjeneste

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerWriter.kt

Det fører til at tekst-søket blir resat.

Replay opprettelse av saker i bruker-api.

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkService.kt

Disabler til det er implementert.

Buggy metric antall_unike_varseltekster

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/resources/bruker.graphql
app/src/main/resources/db/migration/bruker_model/V37__index_notifikasjon_grupperingsid.sql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/Common.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/QuerySakerTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/QuerySakerTidslinjeTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/brukerapiHelpers.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/GraphQLTestFns.kt

Berik saker med tidslinje i bruker-api

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/http/HttpAuthProviders.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/executable/perftest/PerfTest.kt
config/dev-gcp-bruker-api.yaml
config/dev-gcp-produsent-api.yaml
fakedings_token.sh
http/fakedings.http

The old url is deprecated and will be removed soon.

chore: update fakedings url

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/http/HttpAuthProviders.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/executable/perftest/PerfTest.kt
config/dev-gcp-bruker-api.yaml
config/dev-gcp-produsent-api.yaml
fakedings_token.sh
http/fakedings.http

Fakedings url

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/hendelse/Hendelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseService.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/Common.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepositoryTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/EksempelHendelser.kt

Legger til rette for at FristEndre kan være en kilde til påminnelser.

Introduser bestillingHendelseId på PåmminelseOpprettet

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/DataproduktModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Database.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/unblocking/MutexProtectedValue.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDeleteRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseService.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/tid/OsloTid.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseRaceConditionTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseServiceTests.kt
config/prod-gcp-skedulert-paaminnelse.yaml

Håndterer utsatt frist for:
- bruker-api
- dataprodukt
- ekstern-varsling
- skedulert-hard-delete
- statistikk

Håndter FristUtstatt for bruker-api, mm.

---

app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/Common.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/OppgaveMedFristTests.kt

tester utsatt frist på ny, utført, og utgått oppgave

unit tester for utsatt frist i brukerapi

---

.github/workflows/build-and-deploy-fake-api.yaml
fake-produsent-api/Dockerfile
fake-produsent-api/nais-application.yaml
fake-produsent-api/server/esm-require.js
fake-produsent-api/server/package-lock.json
fake-produsent-api/server/package.json
fake-produsent-api/server/produsent.graphql
fake-produsent-api/server/server.js

importert uten historikk fra: git@github.com:navikt/arbeidsgiver-notifikasjon-fake-produsent-api.git
opprinnelig repo er nå satt som archived: https://github.com/navikt/arbeidsgiver-notifikasjon-fake-produsent-api

flytt inn fake produsent api

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/hendelse/Hendelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/manuelt_vedlikehold/ManueltVedlikeholdService.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationHardDeleteNotifikasjon.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationHardDeleteSak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationSoftDeleteNotifikasjon.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationSoftDeleteSak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDeleteService.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/HendelseDeserializationTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/HendelseSerializationTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/HardDeleteTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/SoftDeleteTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepositoryTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDeleteRepositoryEventIntakeTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDeleteRepositoryTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseServiceTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/UtsattFristTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_utgått/FristUtsattTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_utgått/SkedulertUtgåttServiceTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkModelTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/EksempelHendelser.kt

denne er da nullable siden den ikke finnes på kafka fra før

innfør merkelapp på Hard og Soft Delete events

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/HardDeleteSakTests.kt

denne PR tar utgangspunkt i #579 og har derfor den branchen som merge target
- #579

håndter sletting av sak med notifikasjoner atomisk i ProdusentRepository

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/kafka/PartitionAwareHendelsesstrøm.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/manuelt_vedlikehold/ManueltVedlikehold.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/manuelt_vedlikehold/ManueltVedlikeholdService.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseService.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_utgått/SkedulertUtgått.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_utgått/SkedulertUtgåttService.kt

Med denne PR-en er de forskjellige skedulert-tjenestene klare for å bruke sqlite-database med cleanup.

PartitionAwareHendelsesstrøm støtter AutoCloseable prosessorer

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDelete.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDeleteRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDeleteService.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDeleteIdempotensTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDeleteRepositoryEventIntakeTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDeleteRepositoryFindToDeleteTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDeleteRepositoryTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDeleteServiceTest.kt

Reverts navikt/arbeidsgiver-notifikasjon-produsent-api#592

Revert "Atomisk slett av sak i SkedulertHardDelete"

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt

Vi får veldig, veldig trege oppslag. Ser ut til at postgres ikke "dytter" where clause forbi group by i viewene våre.

Bruk subselect i stede for join i notifikasjon-query

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/kafka_reaper/KafkaReaperModel.kt
app/src/main/resources/db/migration/kafka_reaper_model/V3__grupperingsid_merkelapp.sql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/kafka_reaper/KafkaReaperModelIdempotensTest.kt

Test feiler, ingen ting havner i database.

Atomisk sletting kafka reaper

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/local_database/EphemeralDatabase.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseService.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/HardDeleteTests.kt

Tag 2195 skedulert paaminnelse

---

.gitignore
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Database.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/local_database/EphemeralDatabase.kt

Produser metrics for sqlite også. Testet i dev ✅

Measure sqlite-performance in prometheus

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentModel.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/IdempotensOppførselForProdusentApiTests.kt

i erDuplikatAv vil en liste av varsler føre til uuid som ødelegger idempotens i apiet
legg til test og fiks bug

fiks bug relatert til ekterne varsler

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerWriter.kt

tror denne bare er blitt glemt etter en rebuild tidligere

fjern rebuilder som ikke trengs lenger

---

.github/workflows/cicd.yaml
.github/workflows/deploy-dev-manual.yaml
.github/workflows/deploy-replay-validator-prod.yaml

legger merke til at jobber med 20.04 blir stående å vente på ledige runners.

bruk latest runner

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerWriter.kt

TODO: 
https://prometheus.prod-gcp.nav.cloud.nais.io/graph?g0.expr=kafka_consumergroup_group_topic_sum_lag%7Btopic%3D%22fager.notifikasjon%22%2Cgroup%3D%22bruker-model-builder-2-rebuild-nov-2023%22%7D&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h

fjern rebuilder som er ajour

---

app/pom.xml

gjør litt opprydding for å få bedre [risk core](https://console.nav.cloud.nais.io/team/fager)
https://console.nav.cloud.nais.io/team/fager/vulnerabilities
---

oppgrader dependencies

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
config/dev-gcp-produsent-api.yaml

* https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/26

ny produsent Yrkesskade

---

config/dev-gcp-bruker-api.yaml
config/prod-gcp-bruker-api.yaml

Namespace "teamia" skal på sikt fjernes.

Legger til namespace "pia" for min-ia.

---

DEVELOPMENT.md
README.md
REFERENCE.md

blir slik (preview endrinene): 
* https://github.com/navikt/arbeidsgiver-notifikasjon-produsent-api/tree/dokumentasjon 
* https://github.com/navikt/arbeidsgiver-notifikasjon-produsent-api/blob/dokumentasjon/REFERENCE.md

la til dokumentasjon av plattformen

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerAPI.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/QueryNotifikasjonerMedSakTests.kt

sorteringstidspunkt var feil i hentNotifikasjoner

fix bug som gjør at kalenderavtaler ikke blir markert som lest i bjellen

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
config/prod-gcp-produsent-api.yaml

se:
* https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/27

legg til Yrkesskade som produsent i prod

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/altinn/SuspendingAltinnClient.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingServiceTests.kt

Er en god stund siden vi har hatt ustabilitet mot altinn fra bruker-api. Men dersom det oppstår igjen vil denne endringen gjøre at man forsøker på nytt 3 ganger hvis det er en driftsforstyrrelse
https://logs.adeo.no/app/r/s/QZaP9

retry altinn kall i bruker-api

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
config/dev-gcp-produsent-api.yaml

* https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/28

ny produsent i dev teamforeldrepenger

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerWriter.kt

Kan merges når rebuilder er ajour: 
https://prometheus.prod-gcp.nav.cloud.nais.io/graph?g0.expr=kafka_consumergroup_group_topic_sum_lag%7Btopic%3D%22fager.notifikasjon%22%2Cgroup%3D%22bruker-model-rebuild-saksearch%22%7D&g0.tab=0&g0.display_mode=lines&g0.show_exemplars=0&g0.range_input=1h

rm rebuilder for sakstatus search

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
config/dev-gcp-produsent-api.yaml

* https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/29

legg til tiltak-notifikasjon i dev-gcp

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/Dataprodukt.kt

merges når data er rettet i prod

Rm varseltype update

---

app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/PostgresTestListener.kt

På denne måten slipper vi at test databasene vokser og vokser i antall

Endre test databasen til å være numerert og cleares mellom hver kjøring

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/kafka/Config.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/kafka/CoroutineKafkaConsumer.kt

Uten dette vil det dukke opp detaljer fra kilden som kan være identifiserende.

fjern location fra Json mapping exceptions

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
config/dev-gcp-produsent-api.yaml

* https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/31

legg til k9 som ny produsent

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
config/dev-gcp-produsent-api.yaml

* https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/32

oppdater merkelapper og accesspolicy for foreldrepenger

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
config/dev-gcp-produsent-api.yaml

* https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/33

legg til fpinntektsmelding i dev

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt

* https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/34

legg til arbeidstrening merkelapp og servicedef på teamcrm

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt

* https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/35

oppdater edition

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
config/dev-gcp-produsent-api.yaml

* https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/36

fjern ftinntektsmelding

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/SakerMedOppgaveTilstandTests.kt

Tag 2268 ubesvarte kalenderavtaler

---

app/pom.xml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/Bruker.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Metrics.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/GraphQL.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/GraphQLValidation.kt

bump versions

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyStatusSak.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyStatusSakTests.kt

endepunktet vårt hadde ikke implementert riktig respons i henhold til kontrakt.

team tiltak avdekket en mangel i dev

---

app/nais/prod-gcp-produsent-api.yaml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
widget/brukerapi-mock/notifikasjonMockMiddleware.js

Reverts navikt/arbeidsgiver-notifikasjon-produsent-api#748

Revert "Team foreldrepenger prod"

---

app/nais/prod-gcp-produsent-api.yaml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
widget/brukerapi-mock/notifikasjonMockMiddleware.js

Legger til team Foreldrepenger i inbound access policy

Legger til Team Foreldrepenger i prod

---

REFERENCE.md
docs/faq.html

The redirect from intern.nav.no to ansatt.nav.no for this domain will stop working shortly.

Update from intern to ansatt url

---

app/pom.xml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/hendelse/Hendelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNySak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/QueryNotifikasjoner.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkModel.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/Analyze.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/hendelse_transformer/HendelseTransformerTest.kt

og gjør merkelapp påkrevd i fristutsatt og påminnelse endret

Fjern bruk av gamle mottaker typer 

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/GraphQLValidation.kt
app/src/main/resources/produsent.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/EksternVarselApiTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/IdempotensOppførselForProdusentApiTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/InputValideringTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyOppgavePaaminnelseTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/ProdusentRepositoryStub.kt

Uten denne valideringen vil eksternevarsler potensielt feile og føre til manuell arbeid med oppfølging mot teamene som bestilte varslene. Det er bedre at vi feiler der vi vet det ikke kommer til å kunne varsles
Vent med merge av denne til team tiltak har fått ryddet i sin kode:
* https://github.com/navikt/tiltak-notifikasjon/pull/24

legg til validering av tlf er norsk mobilnummer iht nkom

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerWriter.kt
app/src/main/resources/db/migration/bruker_model/V47__drop_mottaker_altinn_enketrettighet.sql

opprydding som kan merges etter at denne er prodsatt:
* https://github.com/navikt/arbeidsgiver-notifikasjon-produsent-api/pull/787

fjern rebuilder og slett gammel tabell

---

app/nais/dev-gcp-bruker-api-writer.yaml
app/nais/prod-gcp-bruker-api-writer.yaml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerWriter.kt

bruk samme postgres bruker i bruker api writer

---

app/nais/dev-gcp-produsent-api.yaml
app/nais/prod-gcp-produsent-api.yaml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt

* https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/41

gi tilgang til yrkesskade saksbehandling i dev og prod

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDelete.kt

fjern rebuild av hard deletes tilstand

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegister.kt

ref:
* https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/44

ny mottaker og merkelapp for tiltak vtao

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/resources/bruker.graphql
app/src/main/resources/db/migration/bruker_model/V51__notifikasjoner_sist_lest.sql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/KlikkPåNotifikasjonGraphQLTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/NotifikasjonPanelApnetTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/Common.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/BrukerRepositoryStub.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/KtorTestServer.kt

Støtte for å sette tidspunkt for når notifikasjoner ble sist lest per bruker (fnr)

Notifikasjon sist lest

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/GraphQL.kt

New attempt to supress cancellation noise.
If the exception cause is CancellationException, then handle and map as a graphql AbortExecutionException.
In the logger exclude Aborts from error logging

handle CancellationException as AbortExecutionException and suppress in log.error

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/GraphQLValidation.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyNotifikasjonFelles.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/EksternVarselApiTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/IdempotensOppførselForProdusentApiTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/InputValideringTest.kt

TLDR
* blank epost og telefon er ugyldig
* epost valideres mot regex
* tlf kan ikke være i en av de blokkerte seriene iht nkom 
* https://nkom.no/telefoni-og-telefonnummer/telefonnummer-og-den-norske-nummerplan/alle-nummerserier-for-norske-telefonnumre
* https://stenonicprdnoea01.blob.core.windows.net/enonicpubliccontainer/numsys/nkom.no/E164.csv

Utvid validering til å blokkere for verdier som vil feile mot altinn
