app/pom.xml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Main.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/QueryModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Altinn.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Database.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/HttpServer.kt
app/src/main/resources/db/migration/V3__indekser_notifikasjon.sql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/PerfTest.kt

Under ytelsestest så vi at podene ble restartet ved relativ lav belastning. 
Det var flere ting som gjorde at dette problemet oppstod. 
Default oppsett på nais er at liveness må svare innen 1 sekund, ellers timer den ut. Etter 3 feilede forsøk vil poden bli restartet.
Flere ting er endret i denne PR. Innføring av dedikerte dispatchere til internal/ bruker og produsent routene.
Litt med ressurser til Netty.
Jeg la også på timer metrikker for kallene til altinn og database, slik at vi fikk se hva som brukte tid. Det avdekket at query mot db tok veldig lang tid. Dette er nå rettet.
Dette medførte en 10x økning i ytelse på både produsent og bruker kallene, samt at podene ikke lenger blir force restarta av k8s.
nyBeskjed fra 50 r/s til 350 r/s 
hentNotifikasjoner fra 1-4 r/s til 50+ r/s. …

hindre at pod blir restartet ved belasting

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/BrukerAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/QueryModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Altinn.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Database.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/GraphQL.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/HttpServer.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Kafka.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/GraphQLTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/PerfTest.kt

ytelsestest i kveld hvor jeg stubbet ut altinn proxy kallet til å returnere alle tilganger for samme virksomhet.
Rampet opp og endte på rundt 300 req/sek i throughput. tilvarer litt over 1 mill req i timen.
Hvert kall returnerte 50 notifikasjoner. 
Når jeg så på min-side-ag i nettleser mens testen kjørte så jeg at notifikasjoner ble hentet med en svartid på rundt 90ms.
kjørte følgende:
```kotlin
client.use {
//nyBeskjed(5000)
(1..10).forEach {
hentNotifikasjoner(it  * 1000)
delay(5000)
}
}
```
```
----------------------------
Ok count: 7000
Error count: 0
req/s: 280
----------------------------
Ok count: 8000
Error count: 0
req/s: 296
----------------------------
Ok count: 9000
Error count: 0
req/s: 300
----------------------------
Ok count: 10000
Error count: 0
req/s: 303 …
```

Nonblocking query model

---

README.md
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Main.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Kafka.kt
http/dev-graphql-query.http

Dette betyr at nye poder ikke får subscribet mens en partisjon er i retry modus.
denne endringen gjør slik at vi pauser partisjonen og seeker til offset, slik at vi kan fortsette å polle som normalt, og rebalance vil ikke bli forhindret.
NB:
Jeg er ikke helt sikker på hvordan pause/resume spiller sammen med en restart. Altså om det er informasjon som overlever kall til subscribe, men jeg vil tro at det ikke gjør det. Dersom det ikke er tilfellet må vi bare eksplisitt resume alle partisjoner når vi subscriber.
---
En mer avansert approach vil være å lagre offsets i databasen, og styre rebalance selv. Dette har noen pros og cons. Cons er at det er mer vi må håndtere og implementere. Pros er at det vil gjøre det enklere for oss å manage offsets og trigge replays uten å lene oss på kafka-cli

mens vi gjør delay vil ikke kafka kunne rebalansere.

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/GraphQLValidation.kt
app/src/main/resources/produsent.graphqls
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/InputValideringTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/GraphQLTestFns.kt

vurderte å låne en mer nøyaktig sjekk for fødselsnummer, f.eks [herfra](https://github.com/navikt/helse-arbeidsgiver-felles-backend/blob/9462b011ee3cbcd30abf23905494eeed1eac5f13/src/main/kotlin/no/nav/helse/arbeidsgiver/web/validation/Validators.kt) men endte med å bare sjekke for 11 digits i første omgang

valider at tekst ikke inneholder fødselsnummer

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Produsent.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/http/HttpAuthProviders.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/http/HttpServer.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegister.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentAPI.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/executable/LocalMainProdusentAPI.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/Common.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/HardDeleteNotifikasjonTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/IdempotensOppførselForProdusentApi.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/InputValideringTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/MineNotifikasjonerTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/NyBeskjedTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/NyOppgaveTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/OppgaveUtførtTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/SoftDeleteNotifikasjonTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/TilgangsstyringTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/KtorTestServer.kt

motivasjon for denne endringen er å kunne bruke produsentid lenger ned i appen.
Ved å skille på definisjon og identifisert produsent så vet vi at dersom vi har en Produsent, så er denne identifisert via oppslag i register.

skill på definisjon og identifisert produsent

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/NærmesteLederService.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/PropagateFromMDCFeature.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/PropagateFromMDCFeatureTests.kt

Dette er nyttig f.eks mot digisyfo nærmesteleder der de plukker ut Nav-Callid

lagt til støtte for å propagere mdc som flere navngitte headere

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingService.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/executable/ekstern_varsling/LocalMainEksternVarsling.kt

1) Exposer emergency_break som metric.
2) Utenfor prod, så er default for AltinnVarselKlient en som bare logger, så ingen vits i å duplisere det.

Expose metric for emergency break

---

app/pom.xml
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker_api/BrukerKlikkGraphQL_QueryModell_IntegrasjonTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/GraphQLTestFns.kt

getTypedContent støtter nå både jsonpath og jsonpointer. 
Alle json paths starter med `$`. Jsonpath har også en del flere features som jeg av og til har savnet i testene.
Som f.eks å plukke ut attributter fra elementer i en liste. (e.g. `$.store.book[*].author`)
readme til jsonpath lib har en del eksempler https://github.com/json-path/JsonPath#path-examples

du vil ikke tro hva som skjedde når TestApplicationResponse.getTypedContent ble kalt med $

---

app/pom.xml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/http/HttpServer.kt

Dette er en liten PoC på å enable out-of-the-box støtte for arbeidsgiver-notifikasjon-widget
Vi vurderte å legge til støtte for jwt vha cookie i backend, men fant ut at det kanskje var bedre å legge den slags funksjonalitet utenfor, så vi laget en egen [frackend/proxy for widgeten](https://github.com/navikt/arbeidsgiver-notifikasjon-widget/pull/12/files#diff-351a953837d40f520006509ae4a28f9cd4a93511dbb403e71462cffdc13a7a1b). Denne overfører selvbetjenings cookie som en Authorization Bearer header før den videresender til backend uten å endre origin. Dette kombinert med cors whitelist i backend gjør det mulig for sider på *.dev.nav.no å hente notifikasjoner uten noe spesielt oppsett annet enn å droppe inn widget på frontenden sin.
må ses i sammenheng med:
* …

enable cors for `*.nav.no` :shipit:

---

app/Dockerfile

hovedmotivasjonen for å fjerne er pga log4j sårbarhet, selv om dette ikke er en reell angrepsvektor i dette tilfellet.
vi får egenglig ikke brukt kafka-cli til å resette offsets via migrering, og siden vi likevel må gjøre dette manuellt er det bedre å ta i bruk aiven cli til den slags https://doc.nais.io/cli/commands/aiven/
fjerner kafka-cli clik at ikke våre images blir flagget som sårbare på nais.

fjern kafka cli fra docker image

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Altinn.kt

slik det er nå så kommer det ganske mange warnings på at respons fra altinn ikke inneholder orgnr.
Dette skjer når altinn returnerer personer.
Det er et flag i klienten `filtrerPåAktiveOrganisasjoner` som kan settes til true, men denne vil da også kun returnere aktive organisasjoner. Vi kan vurdere å sette flagget til true.
Den enkle fiksen er å filtrere ut Personer slik vi gjør med Enterprise.
Dette betyr i praksis at man filtrerer på type==Business.
_Edit: Enn så lenge så filtrerer jeg ut personer uten orgnummer i tilfelle det finnes personer med orgnummer_

reduser log.warn ved kall til altinn

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Altinn.kt

det er en del støy i alerts relatert socket timeout
når dette skjer er det ikke noe vi kan gjøre, gir derfor heller ikke noen mening å logge det som error

det er en del støy i alerts relatert socket timeout

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Altinn.kt

denne logikken blir nok borte så snart vi får fikset grensesnittet i proxyen. Men i mellomtiden vil dette redusere støy i loggene

returner tom liste ved 403

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Database.kt
app/src/main/resources/db/migration/bruker_model/V5__flere_mottakere.sql

Implementerer ny databasemodell for mottakere i bruker-api-modellen.
Lesing fra databasen uendret.
Skriver parallellt til både gamle og nye modell.

write both versions to database

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Bruker.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerModel.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker_api/MottakerMigrationTests.kt

Flytt over gamle notifikasjoner til også å bruke de dedikterte mottaker-tabellene.
Ved å flytte en mottaker pr. sekund, ganger 4 poder, vil ta 80min.
Fremtidige steg (etter at migreringen er utført):
- bytt over lesing til å bruke de nye tabellene
- rydd opp (alter mottaker = nullable, sett null?, vurdere drop column)

migrer mottakere til nye flyt

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/http/HttpServer.kt

I forbindelse med oppgradering av ktor, så har CallLogging begynt å legge på fine farger. Det fungerer dessverre kun i terminaler, ikke i kibana. I Kibana ser et sånn ut:  `[32m200 OK [m:  [36mPOST [m - /api/graphql`

disable colors in log messages

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Produsent.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/main/resources/db/migration/produsent_model/V5__mottakertabeller.sql

Skriver parallelt til gammel og ny skjema.
Kopierer inn i nytt format den gamle dataen.
Når migrering er ferdig, kan vi gå over til å kun bruke den nye.

Oppdaterer produsent-database for å støtte flere mottakere

---

app/src/main/resources/db/migration/produsent_model/V7__drop_mottaker_column_strengthen_constraints.sql

skal ikke deployes før forrige deploy er helt ute.
Kommer til å kjøres i dev før den kjøres i prod, men venter med å gjøre det til approved, siden det ikke er mulig å rulle tilbake.

drop mottaker-kolonne. virksomhetsnummer not null

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Hendelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/GraphQL.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyBeskjed.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyOppgave.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/QueryMineNotifikasjoner.kt
app/src/main/resources/produsent.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/NyBeskjedFlereMottakereTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/EksempelHendelser.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/GraphQLTestFns.kt

Har problem med unit-test. Implementasjonen av mutation-en kaster exception når det er feil, men hadde forventet at det ble en graphql-error, ikke at serveren kræsjet.
```
graphql.GraphqlErrorException: minst 1 mottaker må gis
at graphql.GraphqlErrorException$Builder.build(GraphqlErrorException.java:58)
at no.nav.arbeidsgiver.notifikasjon.Hendelse$BeskjedOpprettet.<init>(Hendelse.kt:289)
at no.nav.arbeidsgiver.notifikasjon.produsent.api.MutationNyBeskjed$NyBeskjedInput.tilDomene(MutationNyBeskjed.kt:62)
at no.nav.arbeidsgiver.notifikasjon.produsent.api.MutationNyBeskjed.nyBeskjed(MutationNyBeskjed.kt:86)
at no.nav.arbeidsgiver.notifikasjon.produsent.api.MutationNyBeskjed.access$nyBeskjed(MutationNyBeskjed.kt:19)
at no.nav.arbeidsgiver.notifikasjon.produsent.api.MutationNyBeskjed$wire$1$1.i …
```

støtte for flere mottakere i graphql

---

.github/workflows/deploy-replay-validator-prod.yaml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Hendelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ReplayValidator.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/kafka/CoroutineKafkaConsumer.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/kafka_reaper/KafkaReaperModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/kafka_reaper/KafkaReaperService.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationHardDelete.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationSoftDelete.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkModel.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/HendelseDeserializationTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/HendelseSerializationTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker_api/HardDeleteTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker_api/SoftDeleteTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/EksempelHendelser.kt

Alle hendelser har nå en aggregateId, en ID som forteller hvilket
aggregate (sak, oppgave, beskjed) hendelsen omhandler.
Det er ingen endring i json-representasjon som følge av denne endringen.

Introduser aggregateId i alle hendelser

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/TilgangerService.kt

Intensjonen er at den kan hente tilganger, passe på
at et feilende kall ikke påvirker andre, og returnere
dem i en passende datastruktur, som inneholder alle tilganger
som ble funnet, og feilene.

Opprett tilganger service

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/GraphQL.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNySak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyStatusSak.kt
app/src/main/resources/produsent.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/NySakTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent_api/NyStatusSakTests.kt

Vi så på hvordan vi kan flate ut input-ene til `nySak` og `nyStatusSak(ByGrupperingsid)`. Vi så egentlig ikke noe behov for å ha input-structene. Så vi gikk for en flat modell.

flat ut argumenter til nySak/nySakStatus mutations

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNySak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyStatusSak.kt
app/src/main/resources/produsent.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/executable/perftest/PerfTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NySakTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyStatusSakTests.kt

Denne endringer er ikke bakoverkompatibel. Men, det er ingen som bruker
dette i prod. Vi har snakket med de to teamene som snart skal deploye til
prod, og de syntes det var greit.
- https://github.com/navikt/permitteringsmelding-notifikasjon/pull/2
- https://github.com/navikt/helse-arbeidsgiver-felles-backend/pull/50

Bruk camel-case i graphql-api.

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepository.kt

siden vi sletter kontaktinfo når ekstern varsling er sendt og kvittert i db, så vil ebrake skrus på med en gang vi ikke har noe aktive utsendinger.
Intensjonen med ebrake var å detektere at vi hadde mistet databasen og på den måten unngå utsending av allerede utsendte notifikasjoner.
Endrer derfor til å sjekke om det finnes en rad i ebrake. Denne tømmes aldri og er populert av migreringsscriptene.
TAG-1892

endre ebrake sjekk slik at den ikke slås på når idle

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/HttpClientMetricsFeature.kt

fjern active requests
featuren ser ut til å fungere lokalt på tvers av klienter.
i dev ser jeg kun metrikker på en klient
i prod ser alle metrikkene ut til å være flate med 0 eller 1 verdi
🤔

http client metric cleanup

---

.github/workflows/cicd.yaml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkModel.kt
docker-compose.yml

det virker som at rekkefølgen på constraint sjekkene ikke er deterministiske. I prod har dette ført til at man har intermittent feil som løser seg selv ved retry av en consumer record.
Litt kjipere er det når feilen oppstår på selve api kallet og vi returnerer feilmelding til produsenten. Da virker det for dem som det feilet, men det gikk faktisk bra likevel.
Denne endringen bør løse det problemet.

gjør conflict sjekk helt generell

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/logging/MaskingAppender.kt

Reverts navikt/arbeidsgiver-notifikasjon-produsent-api#295
Noe gikk veldig galt her som resulterer i at loggene blir tomme.

Revert "legg til maskering av throwableproxy.message også"

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/logging/MaskingAppender.kt

I forrige episode forsøkte jeg å fikse fnr i stacktrace men endte med å fjerne logging 🤦‍♂️ 
i denne episoden tar vi høyde for null og fikser problemet uten å fjerne all logging

ny fiks for maskering av fnr i stacktraces, denne gangen nullsafe

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerModelTests.kt

Denne PRen løser proppen på partisjonen i prod ved at vi hopper over statusoppdateringer på saker som ikke finnes i bruker-api. 
Underliggende feil diskuteres og løses her:
* https://github.com/navikt/arbeidsgiver-notifikasjon-produsent-api/pull/306

hopepr over statusoppdateringer hvos sak ikke finnes

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNySak.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/autoslett/AutoSlettServiceTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/NyLenkeTilSakTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingServiceTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NySakDuplisertTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NySakTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyStatusSakTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/OppgaveUtførtTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/FakeHendelseProdusent.kt

Fra det jeg kan se er dette en bug som skjer dersom to like saker forsøkes opprettes. Denne endringen sørger for at sakId blir riktig på statusoppdateringen, men jeg lurer på om problemet egentlig er logikken i statusoppdateringIkkeRegistrert 🤔
se også:
* https://github.com/navikt/arbeidsgiver-notifikasjon-produsent-api/pull/307

feil i prod hvor to det opprettes statusoppdatering på sakid som ikke finnes

---

app/pom.xml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/tokenx/TokenXClient.kt

A call for access rights has a 1:N fan-out, where all the calls can share tokenx access token.

Cache calls to tokenx.

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/altinn/Altinn.kt

hentTilganger kaller altinn med concurrency og hvis en av disse feiler så blir parent job canceled og hele kallet feiler. Dersom en av de andre sibling coroutines fortsatt pågår,blir denne avbrutt av parenten. Dette er det vi ser i prod i dag.
Vi er litt usikker på akkurat hva som forårsaker feilsituasjonen, men mistenker at det har noe med token exchange og cachingen av dette å gjøre (kanskje i samspill med ktor plugin vi laget). Virker som det av og til havner i en rar state, og da feiler alle påfølgende kall, og en restart av poden løser det.
Oppførselen vi ser står veldig godt beskrevet under Structured concurrency i Coroutines kapittelet i Kotlin Design Patterns and Best Practices:
> It is a very common practice to spawn coroutines from inside another coroutine.
> The first rule of …

forsøk på å fikse slik at samtidige kall ikke avbryter andre ved feil

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Enhetsregisteret.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/HttpClientMetricsFeature.kt

Siden orgnr er en del av path-en i kall mot enhetsregisteret, så blir det alt for stor kardinalitet på eventene (en for hvert orgnr).

reduser kardinalitet på tag i prometheus

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/tokenx/TokenXClient.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/tokenx/TokenXPlugin.kt

Det ser ut som et av cache loader kallene feiler, og så havner vi i en bad state. Dette har vi sett tidligere. Alle påfølgende kall feiler med connection is closed og ParentJob is cancelled, uten at det er så lett å se hvorfor.

legg til try catch rundt exchange

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/logging/LogConfig.kt

Ser ut som noe ble endret i logback som gjør at logconfig stackes. Dvs at det nå er dobbeltlogging både lokalt og i dev/prod.
Har debugget litt og ser at både DefaultJoranConfigurator og BasicConfigurator blir invokert ved oppstart. BasicConfigurator setter da opp en rootlogger med TTLLLayout som er det vi ser lokalt og i prod. Endrer derfor slik at ingen flere configurators invokeres etter vår.
exs:
```
notifikasjon-produsent-api-59979fbcd-qfv45 notifikasjon-produsent-api {"@timestamp":"2022-10-21T08:15:17.333+02:00","@version":"1","message":"processing ConsumerRecord(\n    topic = fager.notifikasjon,\n    partition = 3, \n    offset = 73,\n    timestamp = 1652868287503,\n    key = f7efc02c-6788-45f8-b7ed-a0cb37b94d0e\n)","logger_name":"no.nav.arbeidsgiver.notifikasjon.infrastruktur.kafka …
```

Unngå dobbel logging

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/kafka/CoroutineKafkaConsumer.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/kafka/HendelsesstrømKafkaImpl.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/kafka/PeriodicReplayer.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/Produsent.kt

komponent som trigges hver loop og sjekker om den skal seeke. 
Nå er den satt opp til å seeke 10_000 records tilbake kl 0500 og 100 records tilbake hver time utenfor det. 
Slik det er nå er den ikke default på, men optes inn i hver app
https://prometheus.dev-gcp.nais.io/graph?g0.expr=sum(kafka_consumer_group_offset%7Btopic%3D%22fager.notifikasjon%22%2Cname%3D%22produsent-model-builder%22%7D)&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=2h

PeriodicReplayer: Automatisk delvis replay av hendelser

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/kafka/PartitionAwareHendelsesstrøm.kt

Må fjerne timeren hvis vi mister partisjonen. Hadde vært best med `cancel`, men det finnes ikke.

stop timer of partition revoked

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/GraphQL.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationHardDeleteNotifikasjon.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationHardDeleteSak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyBeskjed.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyOppgave.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNySak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyStatusSak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationOppgaveUtfoert.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationOppgaveUtgaatt.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationSoftDeleteNotifikasjon.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationSoftDeleteSak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyNotifikasjonFelles.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/ProdusentAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/QueryMineNotifikasjoner.kt
app/src/main/resources/db/migration/produsent_model/V13__paaminnelse_eksterne_varsler.sql
app/src/main/resources/db/migration/produsent_model/V14__paaminnelse_eksterne_varsler.sql
app/src/main/resources/produsent.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyOppgavePaaminnelseTests.kt

- fikser deprecated bruk av getContext
- lagrer info om eksterne varsler, og produsent-api returnerer varsel-id-ene i nyOppgave.
Produsent-api sjekker ikke påminnelse-informasjon i idempotens-logikken. Det påvirker ikke de som bruker API-et korrekt, kun dersom noen prøver å oppdatere en oppgave med "nyOppgave" ved å endre påminnelse-feltet.

Paaminnelse produsent api

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/GraphQL.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/GraphQLValidation.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/Error.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyBeskjed.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyOppgave.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNySak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/ProdusentAPI.kt
app/src/main/resources/produsent.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationExceptionTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/GraphQLTestFns.kt

Når det oppstår en uhåndtert feil i kall til produsent api, så bryter vi kontrakt P.T. som resulterer i en misvisende feilmelding til produsent da vi ikek oppfyller kontrakt pga null data, og bare returnerer error.  Dette kommer av en bug i vår kode hvor vi ikke angir hvilket felt feilen er koblet til.
bund ukjent feil til korrekt path
Dersom path ikke er angitt blir det ansett som en ugyldig respons da null ikke er tillatt i skjemadeklarasjonen. 
Mekanismen GraphQL specen angir for å kunne kommunisere at null er korrekt er via path:
Fra spec: 
> If an error can be associated to a particular field in the GraphQL result, it must contain an entry with the key path that details the path of the response field which experienced the error. This allows clients to identify whether a null result …

legg til feilhåndtering ved uhåndtert feil

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/AltinnVarselKlient.kt

Oppdaget i test at dersom serilisering feiler så går det i loop på send. dette skjedde når vi testet en annen serialisering (ifbm #115)

unngå repeated send ved exception i serialisering av respons

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/Produsent.kt

Ser databasen er på 100% cpu. Er nok fordi vi kjører en sekvensiell scan av hele databasen 10 ganger i minuttet pr pod.
Sjekket at migreringen er fullført i prod. Så skrur av.

fjern cleanup processing loop

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/hendelse/Hendelsesstrøm.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/kafka/CoroutineKafkaConsumer.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/kafka/HendelsesstrømKafkaImpl.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/kafka/JsonNodeHendelsesstrømKafkaImpl.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/KafkaHendelsesstrømTests.kt

Kafka-consumer har ikke kjørt parallelt, men har brukt Dispatcher.IO, så poll kan ha skjedd med forskjellige tråder. Bruker derfor thread for å sikre at Kafka-consumer altid kjører i samme tråd.

Metrics for poll-body. Single thread for kafka-consumer.

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Enhetsregisteret.kt

vi gjør potensielt mange kall til ereg per request fra bruker, som kan ende med heng dersom mange av disse blir stående å vente på default rimeout som er 10 sekunder for socket og connect og 20 sekunder for request

set mer aggresiv timeout i ereg klient

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/DataproduktModel.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/EksempelHendelser.kt

Dette er feks tilfelle etter hard delete.
Vi kan enten fjerne fremmednøkkel, men da må vi slette manuelt i stedet for cascade delete eller så kan vi beholde fremmednøkkel og droppe inserts hvor aggregat ikke finnes.
Man kunne vurdert å beholde aggregat idene som er slettet, og hoppe over kun hvis vi vet at aggregatet er slettet ved å sjekke mot slettede ider. Men dette er kanskje godt nok for å få bort blokkeringen.

ignorer brukerklikk hvor aggregat ikke finnes lenger

---

terraform/bigquery.tf
terraform/service_account.tf

Det ser ut som cloud_sql ender med en generert service bruker som ikek er en del av prosjektet. 
Hvorfor dette funker i dev og ikke i prod er fortsatt et mysterie.
Tror dette muligens skaø løse problemet.
Hvis det gjør det kan vi kanskje fjerne den andre service brukeren "sa-notifikasjon-dataprodukt"

Fix bq connection

---

app/src/main/resources/db/migration/dataprodukt_model/V6__indexes_for_deletion.sql

dataprodukt-appen er tregere enn andre apps på replay av kafka. Ser i query insight at det nok er fordi vi ikke har noen indekser for sletting/oppdatering av eksisterende rader.

Database-indekser for dataprodukt

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
config/dev-gcp-produsent-api.yaml

team dialog kommer til å identifisere seg som salesforce. 
ref: 
* https://confluence.adeo.no/x/ydKwGQ
* https://nav-it.slack.com/archives/C02F7211DQ8/p1676983114598859

oppdater til ny client id for å støtte kall gjennom saas-proxy

---

.github/workflows/cicd.yaml

Endre slik at hvis vi manuelt trigger cicd på main så blir det også deployet
Jeg tror vi hadde denne begrensningen for å kunne dele opp build og deploy i dev, og manuelt kunne trigge build/cicd
Dersom noe feiler på main så er det kjekt å kunne trigge den hvis manuelt når det er forstyrrelser feks på github.
I de tilfellene så gir det ikke mening å hoppe over selve deployen tenker jeg. build av main manuelt bør føre til deploy.
oppdaget dette mens jeg forsøkte å teste/fikse deploy oppsettet

når cicd dispatches hopper vi over deploy selv om vi er på main

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/kafka/HendelsesstrømKafkaImpl.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNySak.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/ProdusentModelIdempotensTests.kt

inkluderer fiks for blokkert partisjon
mangler mapping til fornuftig feilmelding dersom race condition skjer i api. Ikke sikkert vi skal legge så mye energi i det.
Har forsøkt å reprodusere race condition på api i unit testuten hell. Feilen har oppstått da jeg via perftest opprettet et sett med saker hvor flere hadde samme merkelapp og grupperingsid. Ikke veldig sannsynlig at noen ville gjort det samme i prod, men det kan skje.

Test som reproduserer situasjon i dev

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/DataproduktModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/hendelse/HardDeletedRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/kafka_reaper/KafkaReaperModel.kt
app/src/main/resources/db/migration/bruker_model/V27__hard_deleted_aggregates.sql
app/src/main/resources/db/migration/dataprodukt_model/V12__hard_deleted_aggregates.sql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerModelIdempotensTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/DataproduktIdempotensTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingIdempotensTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/kafka_reaper/KafkaReaperModelIdempotensTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/ProdusentModelIdempotensTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/EksempelHendelser.kt

we have seen partial replays get stuck on hard deleted aggregates i production.
This can typically become an issue when the hard delete is very close to the origin/create event. Then a partial replay moves the offset to an event on the same aggregate after the create, but prior to the hard delete. This in turn makes the consumer stuck as it can not apply the change event on the aggregate that is deleted. 
```
#example pseudo
offset=0: [origin-event] 
offset=1: [change-event]
offset=2: [hard-delete] <- current-offset
state = deleted
replay to offset=1
PSQL unable to insert fkey missing
```
To remedy this we can track the hard deleted aggregates, and if we encounter an event on a hard deleted aggregate skip the processing.

partial replay on harddeleted aggregates fails in production

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/QuerySakerTests.kt

Nå så blir status-feltete duplisert når vi replayer en topic (eller deler av den). Skrur derfor av støtten for å søke i status-tekst, og klargjør for å kjøre en replay hvor søke-teksten blir resatt til sak-tittelen.

Fjern støtte for søk i status, reset text-søk ved replay

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerWriter.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Database.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNySak.kt
app/src/main/resources/db/migration/bruker_model/V32__sist_endret_paa_sak.sql
app/src/main/resources/db/migration/bruker_model/V33__opprettet_tidspunkt_paa_sak.sql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/QuerySakerTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/PostgresTestListener.kt

Legger grunnlaget for at vi kan sortere saker ut fra `sak`-tabellen uten å merge-joine med `sak_status`-tabellen.
Det kommer PR senere som bruker de nye kolonnene.

Tag 2123 sqlytelse bruker api

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerWriter.kt

Ny replay av topic, som fyller sak-tabellen. Nesten alle saker eksisterer, så med `on conflict do nothing` skjer det jo lite.
Alert i grafana er allerede oppdatert mtp den nye consumer group navnet.

Oppdater eksisterende saker i brukermodel

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Database.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/QuerySakerTests.kt
docker-compose.yml

Dagens SQL har en veldig treg merge-join. Virker som om postgres ikke forstår at saks-listen kun trenger saks-statuser på de 30 valgte sakene, ikke for alle sakene.

Faktoriser ut berikelse av saker i egen sql-spørring

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingService.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingServiceTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/ResumeScheduledJobsTests.kt

Denne endringen gjør at vi beholder metrikken, men kan lage en alert bare dersom wait queue som har elementer hvor tidpunkt har passert over en gitt grenseverdi.

endre waitQueueSizeGauge til å ha tag resume_job_at for past og future

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerApiTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/FeilhåndteringTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/QueryNotifikasjonerMedSakTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/QuerySakerFristTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/QuerySakerTidslinjeTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/SakNotifikasjonKoblingTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/SorteringAvSakerPåFristTest.kt

Tror de tre committene med fordel kan leses hver for seg.
1. Handeleren for GraphQL-queryen `saker` kan bruke info fra tidslinjene for å fylle ut feltene `frister` og `oppgaver`, så den informasjonen kan fjernes fra hoved-spørringen for saker.
2. Fjerner/oppdaterer unittester som sjekker at saker og notifikasjoner tilgangsstyres hver for seg
3. Legger til unitttest som sjekker at grupperingsid-er på tvers av merkelapper ikke blandes sammen. Implementerer dette og fjerner separat tilgangsstyring for saker og notifikasjoner.

Saktilgang overstyrer notifikasjontilgang

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingService.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingServiceTests.kt

En for førstegangs-prosessering av en varsel. En annen for å forsøke feilede varsler på nytt.
Midlertidig implementasjon, så vi ikke må sparke databasen selv.

Split ut to forskjellige prosesserings-løkker for ekstern varsel

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/AltinnVarselKlient.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/AltinnVarselKlientResponse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarsling.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingService.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/AltinnVarselKlientImplTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepositoryTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingServiceTests.kt

altinn-klienten returnerer nå alltid responsen, uavhengig av om den kan retries.
Det gjør responsen tilgjengelig i servicen, så vi kan logge den til en tabell uansett (PR kommer).

Flytter avgjørelse rundt retry ut av AltinnVarselKlient

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/hendelse/Hendelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseService.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/Common.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepositoryTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/EksempelHendelser.kt

Tanker bak feltet er at det gir informasjonen som gjør det mulig å regne ut relative frister. Og da er det når fristen ble opprettet som blir brukt.

Renamer OppgaveOpprettet.{oppgave,frist}OpprettetTidspunkt

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/Error.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationOppgaveUtsettFrist.kt
app/src/main/resources/produsent.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/UtsattFristTests.kt

forslag til å returnere feil dersom ny frist er tidligere enn eksisterende. Gjenbruker Konflikt typen, kan vurdere ny type for denne feilen.

Tag 2087 valider ny frist i api

---

config/dev-gcp-bruker-api.yaml
config/prod-gcp-bruker-api.yaml

Vi bruker ikke API-et, men kafka-topic for tilgangsstyring av nærmeste leder.

Fjern access policy for narmesteleder

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepository.kt
app/src/main/resources/db/migration/ekstern_varsling_model/V9__notifikasjon_koordinat_sak.sql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepositoryTests.kt

Dette løses ved å ta vare på koblingsinformasjon fra opprettet events, for så å rydde disse bort når en hard delete intreffer.

håndter sletting av sak med notifikasjoner atomisk i EksternVarslingRepository

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/Produsent.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNySak.kt
app/src/main/resources/db/migration/produsent_model/V18__hard_deleted_aggregates.sql
app/src/main/resources/produsent.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/EksternVarselApiTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/HardDeleteNotifikasjonTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/HardDeleteSakTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/IdempotensOppførselForProdusentApiTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MineNotifikasjonerTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationExceptionTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyBeskjedFlereMottakereTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyBeskjedTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyOppgaveFlereMottakereTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyOppgavePaaminnelseTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyOppgaveTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NySakDuplisertTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NySakTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyStatusSakTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/OppgaveUtførtTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/OppgaveUtgåttTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/ProdusentModelIdempotensTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/SoftDeleteNotifikasjonTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/SoftDeleteSakTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/UtsattFristTests.kt

Denne PR inneholder i hovedsak to ting:
1. lagre ned info om hard deletes, og skip over hendelser på hard deleted aggregater, på samme måte som i bruker api mm. Dette gjør at vi ikke får en periode med gjennopprettelse og sletting når partisjoner replayes.
2. Blokker opprettelse av sak på koordinat(merkelapp/grupperingsid) som har vært brukt tidligere. Hvis vi tillater produsenter å gjøre det, blir det en del kompleksitet involvert i å sørge for at det oppstår en ny sak med samme id, uten at det blir slettet på nytt. Det enkle her er å blokkere dette i produsent apiet.
TODO:
- vurdert. beholder som duplikatgrupperingsid med konkret feillmelding i tekst

produsent api husker hard deletes og blokkerer gjenbruk av sak koordinat

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/local_database/EphemeralDatabase.kt

Støtte for sqlite-databaser i containeren.
Hvis vi hadde brukt `jdbc:sqlite::mem:` hadde vi bare fått en connection, og måtte ha synkronisert bruk selv.
En `jdbc:sqlite::mem:?cache=shared` vil bare ha én instans, og vi ønsker uavhengige instanser pr. partisjon.
Så oppretter en temp-file, og bruker hikaricp.

SQLite som EphemeralDatabase

---

app/pom.xml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/DataproduktModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarsling.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepositoryImpl.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/http/TimedContentConverter.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/kafka_reaper/KafkaReaperService.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDeleteRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_utgått/SkedulertUtgåttRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/statistikk/StatistikkModel.kt
app/src/main/resources/kotest.properties
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingIdempotensTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepositoryTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingServiceTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingStatusEksportServiceTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EmergencyBreakTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/IdempotentOppgaveOpprettetTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/ResumeScheduledJobsTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationExceptionTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyBeskjedTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyOppgaveTests.kt

setter også language level, dette brekker testene pga diverse issues med måten sealed interfaces håndteres etter 1.6
Feilende test:
- mockk klarer ikke return data class instans av sealed interface: https://github.com/mockk/mockk/issues/1178
- workaround ved å bruke fake repo 7e0725342c992ecbb25d9ac96fd5d02c6a63c78c
Test med workaround:

oppdater kotlin til 1.9

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt

Veldig tregt oppslag i prod (8 sekunder). Virker som om den må bygge opp tabell med alle group-by fra statusoppdateringer_json-viewet.
Basert på explain, så kan det gå raskere her.

Bruk query expression i stede for join

---

app/src/main/resources/db/migration/dataprodukt_model/V13__correct_cast_pseudonymiser.sql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/DataproduktIdempotensTests.kt

Bruk av ::bytea for konvertering til bytea førte til feil hvis teksten inneholdte tegn som kan tolkes som escape characters ('\\').
Bruk av convert_to blir riktig. Stringen skal encodes som den er.

Bruk convert_to for text->bytea konvertering

---

app/src/main/resources/db/migration/kafka_backup_model/V2__partition_offset_index.sql

Hvis man har partition+offset, tar det veldig lang tid å slå opp på event (~20 sek).

Index for raskere oppslag med partition+offset

---

.github/workflows/cicd.yaml

Tanken her er at vi alltid bygger på push og dispatch, mens deploy skjer bare hvis det er en av følgende:
* direkte push på main
* manuell trigg av workflow
* PR blir lukket og merget
Deploy steget passer på å alltid deploye riktig parent på en merge commit, eller github.sha dersom det ikke er en merge commit

optimalisering av bygg og deploy

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/Produsent.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/main/resources/db/migration/produsent_model/V19__kilde_hendelse_eksternt_varsel.sql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/IdempotensOppførselForProdusentApiTests.kt

Som en oppfølger til, eller alternativ til #608 
Bakgrunnen for dette er at healsearbeidsgiver retryer noen kall, og så har varslene blitt sendt, og dermed feiler vi. 
Dersom varslene er like burde kallene anses som idempotente, og ikke feile for dem.
Denne PR utvider duplikatsjekk i produsent api til å ta hensyn til innhold i varsler.
Dette gjøres ved å ta vare på kilden til bestilte varsel, slik at dette kan brukes som grunnlag for sammenligning.
Inneholder også en rebuilder, slik at når denne er ajour så vil vi svare riktig på forespørsler.
TODO før merge:
Etter denne er shippet, er det et par TODOs som må fikses:
* løses her https://github.com/navikt/arbeidsgiver-notifikasjon-produsent-api/pull/610

Utvid duplikatsjekk til å ta hensyn til payload i varsler

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/hendelse/Hendelsesstrøm.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/kafka/HendelsesstrømKafkaImpl.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/Produsent.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingStatusEksportServiceTest.kt

Som oppdaget i #610 så er det mange eksterne varsler som ikke har fått kilde_hendelse satt etter rebuild. 
- #610
Grunnen til dette er at hard delete ikke fører til rydding i tabellene `eksternt_varsel` og `paaminnelse_eksternt_varsel`. 
Her er det ei heller noen fkey med cascade delete.
Siden disse hendelsene har blitt tombstoned og compacted for lengst, så synes jeg det var en god løsning å åpne opp får å lytte på tombstones. I dette tilfellet, så rydder jeg alle varsler som er tilknyttet en notifikasjon med id = tombstone.key. 
Dette vil kun være sant for de tombstonene hvor hendelsen var opprettelse av aggregatet (BeskjedOpprettet, OppgaveOpprettet),
resten vil føre til 0 rows affected, da key er hendelseId / uuid.
Kort oppsummert: 
Gjør det mulig å lytte på tombstones via onTombstone …

Rydd i varsler tilknyttet hard deleted notifikasjoner

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/Error.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyBeskjed.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNyOppgave.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNySak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/ProdusentAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/QueryNotifikasjoner.kt
app/src/main/resources/produsent.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/EksternVarselApiTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/HardDeleteSakTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/HentNotifikasjonTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MineNotifikasjonerTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyBeskjedFlereMottakereTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyOppgaveFlereMottakereTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyOppgaveTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/SoftDeleteNotifikasjonTests.kt

Utvider Error typene `DuplikatEksternIdOgMerkelapp`  og `DuplikatGrupperingsid` med feltet `idTilEksisterende` som reflekterer hva vi anså som eksisterende duplikat.
Nytt endepunkt for å slå opp en Notifikasjon basert på id: `hentNotifikasjon(id: ID!): HentNotifikasjonResultat!`

returner id ved duplikatgrupperingsid

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerWriter.kt
app/src/main/resources/db/migration/bruker_model/V38__sakstatus_oppgitt_mottatt_tidspunkt.sql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/NyLenkeTilSakTests.kt

Som beskrevet i JIRA saken så forsøker Team Helse Arbeidsgiver å oppdatere lenke og tidspunkt via en statusoppdatering på sak med oppgittTidspunkt tilbake i tid.
Det fører i praksis til at saken ser ut som den er uendret, da det blir laget en rad i sak_status, men at en sakstatus med nyere tidsstempel vises som siste.
Denne PRen endrer slik at vi sorterer statusene på mottatt_tidspunkt, men viser tidspunkt hvor tidspunkt enten er oppgittTidspunkt, eller mottattTidspunkt avhengig av om oppgittTidspunkt er null.

Tag 2211 ny status tilbake i tid

---

app/src/main/resources/db/migration/kafka_reaper_model/V4__index_notifikasjon_id.sql

Det er en del tid brukt på replay i reaperen som forårsaker consumer lag.
Dette er på grunn av sprørringen 
`SELECT hendelse_id FROM notifikasjon_hendelse_relasjon WHERE notifikasjon_id = $1`
som bruker 1 sekund i snitt på å kjøre.
Uten denne indeksen:
| QUERY PLAN                                                                         |
|:-----------------------------------------------------------------------------------|
| Seq Scan on notifikasjon\_hendelse\_relasjon  \(cost=0.00..16.50 rows=3 width=16\) |
| Filter: \(notifikasjon\_id = 'xxx'::uuid\)                                         |
Med denne indeksen:
| QUERY PLAN |
| :--- |
| Bitmap Heap Scan on notifikasjon\_hendelse\_relasjon  \(cost=4.17..11.28 rows=3 width=16\) |
|   Recheck Cond: \(notifikasjon\_id = …

legg til index på notifikasjon_id i hendelse_relasjon

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/Main.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/hendelse/Hendelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/kafka/PartitionAwareHendelsesstrøm.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/manuelt_vedlikehold/ManueltVedlikeholdService.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/replay_validator/ReplayValidator.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/replay_validator/ReplayValidatorService.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseService.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_utgått/SkedulertUtgåttService.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/executable/replay_validator/LocalMainReplayValidator.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/replay_validator/ReplayValidatorServiceTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/HardDeleteTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseIdempotensTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelseServiceTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/UtsattFristTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_utgått/FristUtsattTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_utgått/SkedulertUtgåttIdempotensTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_utgått/SkedulertUtgåttServiceTests.kt

dersom det oppdager noen opprettede notifikasjoner på grupperingsid og merkelapp som er slettet så blir det logget en warning og lagt til info i metrikken antall_notifikasjoner_opprettet_etter_delete
TODO: 
* får nok ikke fremprovosert tilstanden, da det kun kan skje ved en race condition

ReplayValidator sjekker etter opprettelser etter hard delete sak

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/tokenx/TokenXClient.kt

Det skjer som regel når det er oppgraderinger i clusteret.
Denne endringen skal gjør oss litt mer robust i de tilfellene.

retry dersom vi får 502 503 eller 504

---

app/src/main/resources/db/migration/kafka_reaper_model/V5__index_gruppering_id_merkelapp.sql

Reaper bruker litt lang til på big leap replay. Ser i cloud console at det er en seq scan på spørringen:
```
INSERT INTO
deleted_notifikasjon (notifikasjon_id,
deleted_at) (
SELECT
hendelse_id AS notifikasjon_id,
$1 AS deleted_at
FROM
notifikasjon_hendelse_relasjon
WHERE
gruppering_id = $2
AND merkelapp = $3)
ON
conflict DO nothing
```

legg til index på gruppering_id merkelapp

---

app/src/main/resources/db/migration/skedulert_harddelete_model/V5__index_gruppering_id_merkelapp.sql

Seq scan fører til lagg alert ved replay leap
```
DELETE
FROM
AGGREGATE
WHERE
merkelapp = $1
AND grupperingsid = $2
```

legg til index for grupperingsid merkelapp

---

app/src/main/resources/db/migration/statistikk_model/V14__indeks_merkelapp_grupperingsid.sql

statistikk-model-builder bruker ca 200ms per hard delete event i prod. Dette gjør at big leap replay i dag tok mer enn 1 time.
```
UPDATE
notifikasjon
SET
hard_deleted_tidspunkt = $1
WHERE
gruppering_id = $2
AND merkelapp = $3
```
| QUERY PLAN |
| :--- |
| Update on notifikasjon  \(cost=0.15..8.17 rows=1 width=258\) |
|   -&gt;  Index Scan using merkelapp\_idx on notifikasjon  \(cost=0.15..8.17 rows=1 width=258\) |
|         Index Cond: \(merkelapp = 'tag'::text\) |
|         Filter: \(gruppering\_id = '42'::text\) |
| QUERY PLAN |
| :--- |
| Update on notifikasjon  \(cost=0.00..1.05 rows=1 width=258\) |
|   -&gt;  Seq Scan on notifikasjon  \(cost=0.00..1.05 rows=1 width=258\) |
|         Filter: \(\(gruppering\_id = '42'::text\) AND \(merkelapp = 'tag'::text\)\) |

legg til index på grupperingid merkelapp

---

app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/QueryKommendeKalenderavtalerTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/QuerySakerTidslinjeTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/GraphQLTestFns.kt

Dette hadde påvirkning på tester på sak.
Må se nærmere på en proper fix, men endrer tilbake deserialization feature først
Fikk ikke testfeil på branch før etter merge, som er veldig rart 🤔 
Tester på main feiler nå, så jeg rullet tilbake endring av laxObjectMapper i test og heller gjorde en temp workaround på de testene som var litt wonky.
Tenker å se på å få til en tilsvarende fix som tidligere, hvor dato blir serdes med offset hvis angitt. Så slipper vi masse workarounds i tester fordi man går fra +1 til Z gjennom jackson

fjern deserialization config fra test

---

.github/workflows/cicd.yaml
.github/workflows/deploy-replay-validator-prod.yaml

Det er en del støy på endringer gjort i ./test-produsent og ./fake-produsent-api som følge av det "optimaliserte" oppsettet. Støyen er i form av image pull backoff på deploy når det ikke er laget noen produsent-api image på kodeendringer i disse sub mappene. Det kan la seg gjøre å fikse dette med enda mer konfig, men tenker det er bedre å gå tilbake til et enklere oppsett.
Hensikten  med optimaliseringen var å få ned turnaround på merge til prod, men det kom på bekostning av et litt mer komplisert oppsett. Nå som byggtiden er redusert er det ikke like mye verdt det med et mer komplisert oppsett.
reverter endringen gjort her:
* https://github.com/navikt/arbeidsgiver-notifikasjon-produsent-api/pull/606
se også
* https://github.com/navikt/arbeidsgiver-notifikasjon-produsent-api/pull/649

Endrer build pipeline tilbake til bygg og push

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/kafka/Config.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/KafkaSerializerTests.kt

Fjerner workaround for korrupt event i dev.
Kan merges når tomstone er compactet. Bør ta ca 7 dager fra den ble tomstonet. tombstone er på
| partition | offset | timestamp |
| :--- | :--- | :--- |
| 12 | 87018 | 1712068860201 |
compaction kan sjekkes med:
```
./kafka-console-consumer.sh --bootstrap-server $KAFKA_BROKERS \
--consumer.config $KAFKA_CONFIG/kafka.properties \
-topic fager.notifikasjon \
--formatter kafka.tools.DefaultMessageFormatter \
--property print.key=true --property print.value=true --property print.offset=true --property print.timestamp=true \
--partition 12 --offset 80148 --max-messages 5
```
ref:
* https://github.com/navikt/arbeidsgiver-notifikasjon-produsent-api/pull/667

remove corrupt event bugfix

---

.github/workflows/codeql.yml
app/pom.xml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/AltinnVarselKlient.kt
app/src/main/resources/wsdl/NotificationAgencyExternalBasic.svc.wsdl
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/AltinnVarselKlientImplTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepositoryTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingServiceTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/MockAltinnServer.kt

skriver bort fra nav tjenestespesifikasjoner da denne fortsatt er låst til java 8 / javax. cxf 4 krever jakarta.
Funksjonalitet skal være uberørt, men bør testes i dev før merge.
TODONE:

bump cxf og kafka

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/AltinnVarselKlient.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Util.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/altinn/SuspendingAltinnClient.kt

Innimellom får vi 500 feil med tom body.
Litt uklart hva den underliggende årsaken er, men det løser seg etter en delayed retry.
For å unngå støy i loggene på dette kan vi forsøke et par retry med en gang på denne typen feil.

retry WstxEOFException i AltinnVarselKlient

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerWriter.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/QuerySakerTests.kt

denne gang med en idempotent variant.
Nå populeres saksearch basert på innhold i sak og sak_status tabellene. Da skal de ikke bli resource leak ved replay som var utgangspunkt for at dette ble fjernet. ref: #493 / 995cc2166aff5492637b0131f1df8d45e8fe1772

gjeninføre søk på statustekst

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/QuerySak.kt
app/src/main/resources/produsent.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/HentSakTests.kt

Team Foreldrepenger har etterspurt denne funksjonaliteten.
De ønsker å kunne slå opp status for å avgjøre om saken må gjenåpnes.

eksponer sisteStatus på sak via hentSak queries

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/produsenter/ProdusentRegisterImpl.kt
config/dev-gcp-produsent-api.yaml

Det er ingen outbound policy eller kode som kaller oss i denne appen: 
* https://github.com/navikt/tiltak-refusjon-api/blob/master/.nais/nais.yml
* https://github.com/navikt/arbeidsgiver-notifikasjon-produsenter/pull/37

fjern tiltak-refusjon-api. er ikke i bruk

---

app/pom.xml

Bumps org.apache.cxf:cxf-rt-transports-http from 4.0.4 to 4.0.5.
closes #728 which fails image push due to long branch name 
---
updated-dependencies:
- dependency-name: org.apache.cxf:cxf-rt-transports-http dependency-type: direct:production ...

Bump org.apache.cxf:cxf-rt-transports-http from 4.0.4 to 4.0.5 in /app

---

app/Dockerfile
app/nais/dev-gcp-bruker-api-writer.yaml
app/nais/dev-gcp-bruker-api.yaml
app/nais/dev-gcp-dataprodukt.yaml
app/nais/dev-gcp-ekstern-varsling.yaml
app/nais/dev-gcp-hendelse-transformer.yaml
app/nais/dev-gcp-kafka-backup.yaml
app/nais/dev-gcp-kafka-reaper.yaml
app/nais/dev-gcp-manuelt-vedlikehold.yaml
app/nais/dev-gcp-produsent-api.yaml
app/nais/dev-gcp-replay-validator.yaml
app/nais/dev-gcp-skedulert-harddelete.yaml
app/nais/dev-gcp-skedulert-paaminnelse.yaml
app/nais/dev-gcp-skedulert-utgaatt.yaml
app/nais/dev-gcp-statistikk.yaml
app/nais/prod-gcp-bruker-api-writer.yaml
app/nais/prod-gcp-bruker-api.yaml
app/nais/prod-gcp-dataprodukt.yaml
app/nais/prod-gcp-ekstern-varsling.yaml
app/nais/prod-gcp-kafka-backup.yaml
app/nais/prod-gcp-kafka-reaper.yaml
app/nais/prod-gcp-produsent-api.yaml
app/nais/prod-gcp-replay-validator.yaml
app/nais/prod-gcp-skedulert-harddelete.yaml
app/nais/prod-gcp-skedulert-paaminnelse.yaml
app/nais/prod-gcp-skedulert-utgaatt.yaml
app/nais/prod-gcp-statistikk.yaml

Resource utilization can be viewed in the nais console: https://console.nav.cloud.nais.io/team/fager/utilization
This PR fikses a couple of things:
1. explicitly define the resource requests in dev, so it will be easier to adjust to reduce overage
2. align the resource requests in production so it will be easier to adjust to reduce overage
3. fixes regression where we lost maxrampercentage jvm opts after moving to distroless. Distroless images do not respect `JAVA_OPTS`, the same way the old baseimages do. To achieve the same result in distroless set `JDK_JAVA_OPTIONS`.
Demonstrated by the following test using docker:
```Dockerfile
FROM gcr.io/distroless/java21-debian12
COPY target/app.jar app.jar
COPY target/lib lib
ENV JAVA_OPTS='-XX:MaxRAMPercentage=75'
#ENV …
```

Improve resource utilization

---

widget/brukerapi-mock/package-lock.json
widget/brukerapi-mock/package.json
widget/component/package-lock.json
widget/component/package.json
widget/component/src/NotifikasjonWidget/NotifikasjonPanel/Dropdown.css

Nå blir dropdown fra notifikasjonsbjellen opp til 30 rem bred. Det er for å tilpasse størrelsen som blir tilgjengelig av bedriftwsmenyen. Dermed blir bedriftsmenyen og notifikasjon-dropdown like brede.

Widget-meny blir opp til 30rem bred

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/kafka_reaper/KafkaReaperModel.kt

når en harddelete gjøres på sak så sjekker kafka reaper om det finnes noen notifikasjoner på koordinatet merkelapp::grupperingsid som skal slettes. Dette manglet for kalenderavtale.
Ingen som har tatt det i bruk enda, så det krever ikke rydding så vidt jeg kan se.

kobling fra sak til kalenderavtale manglet i reaper

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/DataproduktModel.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/hendelse/HardDeletedRepository.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/hendelse/Hendelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/ProdusentRepository.kt
app/src/main/resources/db/migration/bruker_model/V48__hard_deleted_via_cascade.sql
app/src/main/resources/db/migration/dataprodukt_model/V17__mottaker_altinn_ressurs.sql
app/src/main/resources/db/migration/dataprodukt_model/V18__hard_deleted_via_cascade.sql
app/src/main/resources/db/migration/produsent_model/V29__hard_deleted_via_cascade.sql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerModelIdempotensTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/DataproduktIdempotensTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepositoryTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingServiceTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/ProdusentModelIdempotensTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/util/Utils.kt
terraform/bigquery.tf

fikser bug der replay fører til at notifikasjoner som er hard delete via cascade fra sak gjennoppstår.
fikser: https://trello.com/c/8IgQTllr/117-feil-rundt-harddelete-og-kafka-replay-i-brukerapi

støtte cascade delete fra sak i HardDeletedRepository

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/replay_validator/ReplayValidator.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/replay_validator/ReplayValidatorService.kt

i noen tilfeller blir service metrikk pollet før repoet faktisk var instansiert. Dette medførte en nullpointer.
Endrer koden slik at det blir litt mer tydelig at intensjonen er at repoet skal være instansiert før service er klar til prosessering.
```
java.lang.NullPointerException: Cannot invoke "no.nav.arbeidsgiver.notifikasjon.replay_validator.ReplayValidatorRepository.findNotifikasjonCreatesAfterHardDeleteSak()" because "this.repository" is null
at no.nav.arbeidsgiver.notifikasjon.replay_validator.ReplayValidatorService.updateMetrics(ReplayValidatorService.kt:93)
at no.nav.arbeidsgiver.notifikasjon.replay_validator.ReplayValidator$main$1$2.invokeSuspend(ReplayValidator.kt:36)
at no.nav.arbeidsgiver.notifikasjon.replay_validator.ReplayValidator$main$1$2.invoke(ReplayValidator.kt)
at …
```

assign repository før service legges til i processors

---

app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NySakTests.kt

fant denne branchen liggende. Ser ut som noe som skulle være med på main

Tester max-lengde og sensitivInformasjon på tittel

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/GraphQL.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/http/HttpAuthProviders.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/http/HttpServer.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/KalenderavtaleTests.kt

Denne settes opp i callLogging plugin, men der propageres det ikke. Den blir kun satt på logg kallet til slitt når responsen går ut.
Muligens relevant: https://youtrack.jetbrains.com/issue/KTOR-6862/CallLogging-Auth-principal-isnt-available-in-MDC-entry-provider-since-2.3.8#focus=Comments-27-9679688.0-0
se også denne tråden på slack: https://nav-it.slack.com/archives/C9T4KG12M/p1734687935473459

propager appname til mdc

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDeleteRepositoryImpl.kt

Her gjorde jeg en glipp når jeg fikset feilen i skedulert hard delete. Når jeg tok i bruk HardDeletedRepository så gjorde jeg det likt som i produsent api, hvos vi også sjekker soft deletes. DEtte er vanligvis korrekt, men _ikke_ når det gjelder skedulering av hard deletes. Setter derfor tilbake til noop på soft delete.

soft delete skal ikke påvirke hard deletes

---

app/src/main/resources/db/migration/bruker_model/V50__add_index_kobling_notifikasjon.sql
app/src/main/resources/db/migration/dataprodukt_model/V19__add_index_kobling_notifikasjon.sql
app/src/main/resources/db/migration/produsent_model/V30__add_index_kobling_notifikasjon.sql
app/src/main/resources/db/migration/skedulert_harddelete_model/V7__add_index_kobling_notifikasjon.sql
app/src/main/resources/db/migration/skedulert_utgatt_model/V2__add_index_kobling_notifikasjon.sql
app/src/main/resources/produsent.graphql

Jeg tenkte at uniq indeksen tok seg av dette, men det virker ikke sånn.
Dette så vi når vi bygget skedulert-utgatt modellen [fra bunnen av i helgen](https://prometheus.prod-gcp.nav.cloud.nais.io/query?g0.expr=kafka_consumergroup_group_topic_sum_lag%7Btopic%3D%22fager.notifikasjon%22%2Cgroup%21%7E%22null%7Cskedulert-utgaatt-1%7Cskedulert-utgatt-model-builder%7Cskedulert-paaminnelse.*%7Creplay-validator%7Cmanuelt-vedlikehold-.*%7C.*rebuild.*%22%7D&g0.show_tree=0&g0.tab=graph&g0.end_input=2025-01-18+07%3A51%3A14&g0.moment_input=2025-01-18+07%3A51%3A14&g0.range_input=1d&g0.res_type=auto&g0.res_density=medium&g0.display_mode=lines&g0.show_exemplars=0). 
Fra dokumentasjonen: https://www.postgresql.org/docs/current/indexes-multicolumn.html
A multicolumn B-tree index can be used with query …

legg til index for å hindre seq scan

---

.github/workflows/platform_build_and_deploy.yaml
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/Dataprodukt.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingService.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/Database.kt
app/src/main/resources/db/migration/dataprodukt_model/V3__grant_access_dataprodukt_service_user.sql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingServiceTests.kt
docker-compose.yml

altinn 3 kan feile synkront(http400) og asynkront (sendestatus).
De asynkrone feilene er allerede håndtert, men det var en mangel på håndtering av synkrone feil. Disse ble ikke kvittert og derfor ble jobben poppet inn og ut av job queue med timeout på lock.

kvitter synkrone feil fra altinn

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/Altinn3VarselKlient.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingService.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/GraphQL.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/GraphQLValidation.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/FellesGraphQLTypes.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationKalenderavtale.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationNySak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/MutationTilleggsinformasjonSak.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyNotifikasjonFelles.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/ProdusentAPI.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/QueryNotifikasjoner.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelse.kt
app/src/main/resources/produsent.graphql
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/Altinn3VarselKlientImplTest.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingServiceTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/InputValideringTests.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/api/NyOppgavePaaminnelseTests.kt
test-produsent/src/Komponenter/EksternVarsling.tsx
test-produsent/src/Komponenter/NyOppgave.tsx

Endrer fra validering med graphql directives, til en mer eksplisitt validering i DTOene.
Dette gjør at valideringen er mindre magisk, lettere å utvide, samt mer garantert å fungere som forventet. Krevde en liten endring i feilhåndteringslogikken i  TypeRuntimeWiring.Builder.coDataFetcher (GraphQL.kt) Siden jackson pakker inn feil i DTOer som deserialiseres via objectMapperen. Der er det nå endret til å sjekke om RuntimException er forårsaket av en ValideringsFeil og i såfall håndtere den som en valideringsfeil, hvis ikek gjør den som før.
---
og forresten, oppdaget at ressursId støtte manglet på varsel ved påminnelse 😬 , sniker det inn her

rework input validation

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarslingRepository.kt

Dette ser ut til å skje fordi to processing loops forsøker å gjøre det samme:
`requeue-lost-work` går hvert 10. minutt og oppretter jobber for varsler som ikke er ferdige og ikke allerede ligger i job queue
`resume-scheduled-work` går hvert 5. minutt og flytter ting som ligger på wait_queue til job_queue
Feilmeldingen oppstår når en varsling som ligger i wait queue blir forsøkt opprettet av requeue-lost-work.
Dette skjer fordi de kjører omtrent samtidi siden 10 og 5 har overlapp hvert 10. minutt. Det vil også kunne skje når en pod restartes siden det ikek er en initiell pause på loppene.
Eksempel fra prod logger. 2 log linjer omtrent samtidig. Samme pod. Viser at loopene går i beina på hverandre:
```
[
{
"cluster": [
"prod-gcp"
],
"pod": [
"notifikasjon-ekstern-varsling-7746b7b8f8-k5cvg" …
```

får regelmessige feilmelding på requeue

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepository.kt
app/src/test/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerRepositorySearchTest.kt

Dette gjør at søk på f.eks. "070307" matcher "07.03.07" i teksten. La også til relevante testdata og dekning i eksisterende søketester.

Forbedret søk på tall ved å splitte søketerm med >=4 siffer i chunks av 2

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/graphql/GraphQL.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/infrastruktur/http/HttpServer.kt

Når en klient avbryter en request så ender det som en cancellation. Ekssiterende feilhåndtering gjør dette til en GraphQLError og logger det som en feil. (2 log error per slik feil)
Denne endringen forsøker å sørge for at cancellation blir respektert, og at det ikke logges som støy.

Ikke propager cancellation exception som en graphql error.

---

app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/Bruker.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/bruker/BrukerWriter.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/dataprodukt/Dataprodukt.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/ekstern_varsling/EksternVarsling.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/kafka_backup/KafkaBackup.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/kafka_bq/KafkaBQ.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/kafka_reaper/KafkaReaper.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/produsent/Produsent.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/replay_validator/ReplayValidator.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_harddelete/SkedulertHardDelete.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_påminnelse/SkedulertPåminnelse.kt
app/src/main/kotlin/no/nav/arbeidsgiver/notifikasjon/skedulert_utgått/SkedulertUtgått.kt

Vi får en del feil av typen: 
`EmbeddedServer was stopped at io.ktor.server.engine.EmbeddedServer.currentApplication`
og `kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms\n\tat kotlinx.coroutines.TimeoutKt.TimeoutCancellationException` Ved deploy og autoscaling.
Dette ser ut til å skyldes at noen tjenester settes opp (og av og til feiler) før serveren er startet.
Med denne endringen flyttes alt av oppsett inn i strukturert concurrency under ktor serveren.

fjerner runBlocking fra main og flytter init inn i embeddedServer
